export const sampleProperties = [
  {
    id: 1,
    location: "New York",
    propertyType: "Residential",
    subtype: "Flat",
    bedrooms: 2,
    budget: 80000,
  },
  {
    id: 2,
    location: "Los Angeles",
    propertyType: "Residential",
    subtype: "House",
    bedrooms: 3,
    budget: 120000,
  },
  {
    id: 3,
    location: "Chicago",
    propertyType: "Commercial",
    subtype: "Shop/Showroom",
    budget: 150000,
  },
  {
    id: 4,
    location: "San Francisco",
    propertyType: "Other",
    subtype: "Farm House",
    budget: 200000,
  },
  {
    id: 5,
    location: "Miami",
    propertyType: "Residential",
    subtype: "Condo",
    bedrooms: 1,
    budget: 60000,
  },
  {
    id: 6,
    location: "Seattle",
    propertyType: "Residential",
    subtype: "Apartment",
    bedrooms: 2,
    budget: 100000,
  },
  {
    id: 7,
    location: "Dallas",
    propertyType: "Commercial",
    subtype: "Office Space",
    budget: 120000,
  },
  {
    id: 8,
    location: "Denver",
    propertyType: "Other",
    subtype: "Cabin",
    budget: 180000,
  },
  {
    id: 9,
    location: "Boston",
    propertyType: "Residential",
    subtype: "Duplex",
    bedrooms: 4,
    budget: 150000,
  },
  {
    id: 10,
    location: "Atlanta",
    propertyType: "Residential",
    subtype: "Townhouse",
    bedrooms: 3,
    budget: 110000,
  },
  {
    id: 11,
    location: "Houston",
    propertyType: "Commercial",
    subtype: "Restaurant",
    budget: 200000,
  },
  {
    id: 12,
    location: "Phoenix",
    propertyType: "Other",
    subtype: "Ranch",
    budget: 250000,
  },
  {
    id: 13,
    location: "Philadelphia",
    propertyType: "Residential",
    subtype: "Loft",
    bedrooms: 1,
    budget: 75000,
  },
  {
    id: 14,
    location: "San Diego",
    propertyType: "Residential",
    subtype: "Penthouse",
    bedrooms: 3,
    budget: 180000,
  },
  {
    id: 15,
    location: "Detroit",
    propertyType: "Commercial",
    subtype: "Warehouse",
    budget: 130000,
  },
  {
    id: 16,
    location: "Portland",
    propertyType: "Other",
    subtype: "Barn",
    budget: 160000,
  },
  {
    id: 17,
    location: "Las Vegas",
    propertyType: "Residential",
    subtype: "Studio",
    bedrooms: 1,
    budget: 70000,
  },
  {
    id: 18,
    location: "Minneapolis",
    propertyType: "Residential",
    subtype: "Cottage",
    bedrooms: 2,
    budget: 90000,
  },
  {
    id: 19,
    location: "Charlotte",
    propertyType: "Commercial",
    subtype: "Salon",
    budget: 110000,
  },
  {
    id: 20,
    location: "Austin",
    propertyType: "Other",
    subtype: "Treehouse",
    budget: 120000,
  },
  {
    id: 21,
    location: "Raleigh",
    propertyType: "Residential",
    subtype: "Mansion",
    bedrooms: 5,
    budget: 300000,
  },
  {
    id: 22,
    location: "Tampa",
    propertyType: "Residential",
    subtype: "Bungalow",
    bedrooms: 2,
    budget: 95000,
  },
  {
    id: 23,
    location: "Salt Lake City",
    propertyType: "Commercial",
    subtype: "Fitness Center",
    budget: 180000,
  },
  {
    id: 24,
    location: "Orlando",
    propertyType: "Other",
    subtype: "Houseboat",
    budget: 140000,
  },
  {
    id: 25,
    location: "Nashville",
    propertyType: "Residential",
    subtype: "Cabin",
    bedrooms: 3,
    budget: 120000,
  },
];
