export const Properties = [
    {
      image: "https://i.pinimg.com/736x/32/74/e1/3274e11e331e935c60aa3784946079a8.jpg",
      image2: "https://i.pinimg.com/736x/32/74/e1/3274e11e331e935c60aa3784946079a8.jpg",
      image3: "https://i.pinimg.com/736x/32/74/e1/3274e11e331e935c60aa3784946079a8.jpg",
      image4: "https://i.pinimg.com/736x/32/74/e1/3274e11e331e935c60aa3784946079a8.jpg",
      image5: "https://i.pinimg.com/736x/32/74/e1/3274e11e331e935c60aa3784946079a8.jpg",
      city: "Bhopal",
      state: "MP",
      pincode: 481661,
      BookingAmount: 50000,
      SECTOR: 62,
      Address: "Kiran Garden, New Delhi, Kiran Garden, New Delhi - West, Delhi NCR",
      Landmarks: "Nawada metro station",
      Lift: 1,
      propertyType: "Residential",
      SubpropertyType: "Apartment",
      bedrooms: 2,
      price: 120000,
      bathrooms: 1,
      updatedOn: "January 15, 2023",
      garages: 1,
      area: "800 sq. ft.",
      yearBuilt: 2015,
      description: "The first impression counts. And this one is truly mighty and majestic. The palatial elevation of Paras Emperor piques the curiosity of visitors. What they will see inside will simply exceed their expectations! Welcome to our spa",
    },
    {
      image: "https://example.com/city2_image.jpg",
      image2: "https://example.com/city2_image2.jpg",
      image3: "https://example.com/city2_image3.jpg",
      image4: "https://example.com/city2_image4.jpg",
      image5: "https://example.com/city2_image5.jpg",
      city: "Mumbai",
      state: "MH",
      pincode: 400001,
      BookingAmount: 60000,
      SECTOR: 45,
      Address: "Marine Drive, Mumbai",
      Landmarks: "Gateway of India",
      Lift: 2,
      propertyType: "Commercial",
      SubpropertyType: "Office Space",
      bedrooms: 0,
      price: 150000,
      bathrooms: 2,
      updatedOn: "February 20, 2023",
      garages: 0,
      area: "1200 sq. ft.",
      yearBuilt: 2018,
      description: "Modern and spacious office space with a stunning view of the Arabian Sea. Perfect for businesses looking for a prime location.",
    },
    {
      image: "https://example.com/city3_image.jpg",
      image2: "https://example.com/city3_image2.jpg",
      image3: "https://example.com/city3_image3.jpg",
      image4: "https://example.com/city3_image4.jpg",
      image5: "https://example.com/city3_image5.jpg",
      city: "Chennai",
      state: "TN",
      pincode: 600001,
      BookingAmount: 45000,
      SECTOR: 30,
      Address: "Anna Nagar, Chennai",
      Landmarks: "Marina Beach",
      Lift: 1,
      propertyType: "Residential",
      SubpropertyType: "Villa",
      bedrooms: 4,
      price: 250000,
      bathrooms: 3,
      updatedOn: "March 10, 2023",
      garages: 2,
      area: "2000 sq. ft.",
      yearBuilt: 2016,
      description: "Luxurious villa with a private garden and modern amenities. Ideal for families seeking a premium living experience.",
    },
    {
      image: "https://example.com/city4_image.jpg",
      image2: "https://example.com/city4_image2.jpg",
      image3: "https://example.com/city4_image3.jpg",
      image4: "https://example.com/city4_image4.jpg",
      image5: "https://example.com/city4_image5.jpg",
      city: "Kolkata",
      state: "WB",
      pincode: 700001,
      BookingAmount: 55000,
      SECTOR: 55,
      Address: "Park Street, Kolkata",
      Landmarks: "Victoria Memorial",
      Lift: 1,
      propertyType: "Commercial",
      SubpropertyType: "Retail Space",
      bedrooms: 0,
      price: 180000,
      bathrooms: 1,
      updatedOn: "April 5, 2023",
      garages: 0,
      area: "1000 sq. ft.",
      yearBuilt: 2017,
      description: "Prime retail space in the heart of the city. High footfall area with excellent visibility for your business.",
    },
    {
      image: "https://example.com/city5_image.jpg",
      image2: "https://example.com/city5_image2.jpg",
      image3: "https://example.com/city5_image3.jpg",
      image4: "https://example.com/city5_image4.jpg",
      image5: "https://example.com/city5_image5.jpg",
      city: "Hyderabad",
      state: "TS",
      pincode: 500001,
      BookingAmount: 48000,
      SECTOR: 40,
      Address: "HiTech City, Hyderabad",
      Landmarks: "Cyber Towers",
      Lift: 2,
      propertyType: "Residential",
      SubpropertyType: "Penthouse",
      bedrooms: 3,
      price: 200000,
      bathrooms: 2,
      updatedOn: "May 12, 2023",
      garages: 1,
      area: "1500 sq. ft.",
      yearBuilt: 2019,
      description: "Elegant penthouse with panoramic views of the city. Contemporary design and top-notch amenities for a luxurious lifestyle.",
    },
  ];
  